server:
  port: 8002

dubbo:
  registry:
    address: nacos://localhost:8848
    group: sample-demo
  application:
    name: generic-consumer
    qos-enable: false
  protocol:
    name: dubbo
    port: 20881


