server:
  port: 8001

spring:
  application:
    name: sample-provider


dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://localhost:8848
    group: sample-demo
  protocol:
    name: dubbo
    port: 20880
  metadata-report:
    address: nacos://127.0.0.1:8848