server:
  port: 8002

spring:
  application:
    name: sample-consumer

dubbo:
  registry:
    address: nacos://localhost:8848
    group: sample-demo
  application:
    name: sample-consumer
    qos-enable: false
  protocol:
    name: dubbo
    port: 20881

