server:
  port: 8003

spring:
  application:
    name: sample-provider

dubbo:
  registry:
    address: nacos://localhost:8848
    group: sample-demo
  application:
    name: sample-provider2
    qos-enable: false
  protocol:
    name: dubbo
    port: 20882

# tracing信息输出到logging
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'