server:
  port: 8030

dubbo:
  registry:
    address: nacos://localhost:8848
    group: sample-demo
  application:
    name: async-provider
    qos-enable: false
  protocol:
    name: dubbo
    port: 20810
