server:
  port: 8002

spring:
  application:
    name: sample-consumer

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://localhost:8848
    group: sample-demo
  metadata-report:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20881
