server:
  port: 8001

dubbo:
  registries:
    beijingRegistry:
      address: nacos://localhost:8848
      group: sample-demo
    hangzhouRegistry:
      address: zookeeper://localhost:2181
      group: sample-demo
  application:
    name: generic-provider
    qos-enable: false
  protocol:
    name: dubbo
    port: 20880
