server:
  port: 8009

dubbo:
  registry:
    address: nacos://localhost:8848
    group: sample-demo
  application:
    name: async-consumer
    qos-enable: false
  protocol:
    name: dubbo
    port: 20881
  consumer:
    timeout: 10000


